# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['mainapp.py',
	"/home/frank/Desktop/interface_lastversion/bestpatch.py",
	"/home/frank/Desktop/interface_lastversion/configuration.py",
	"/home/frank/Desktop/interface_lastversion/detect.py",
	"/home/frank/Desktop/interface_lastversion/fillfront.py",
	"/home/frank/Desktop/interface_lastversion/Graphicview.py",
	"/home/frank/Desktop/interface_lastversion/image_merge.py",
	"/home/frank/Desktop/interface_lastversion/image_split.py",
	"/home/frank/Desktop/interface_lastversion/inpainting.py",
	"/home/frank/Desktop/interface_lastversion/Insertion_db.py",
	"/home/frank/Desktop/interface_lastversion/Listwidget.py",
	"/home/frank/Desktop/interface_lastversion/Listwidgetitem.py",
	"/home/frank/Desktop/interface_lastversion/priorities.py",
"/home/frank/Desktop/interface_lastversion/Tablewidget.py",
"/home/frank/Desktop/interface_lastversion/Thread.py",
"/home/frank/Desktop/interface_lastversion/Thread_inpainting.py",
"/home/frank/Desktop/interface_lastversion/Treeview.py",
"/home/frank/Desktop/interface_lastversion/update.py",
"/home/frank/Desktop/interface_lastversion/models/__init__.py",
"/home/frank/Desktop/interface_lastversion/models/common.py",
"/home/frank/Desktop/interface_lastversion/models/experimental.py",
"/home/frank/Desktop/interface_lastversion/models/export.py",
"/home/frank/Desktop/interface_lastversion/models/yolo.py",
"/home/frank/Desktop/interface_lastversion/utils/activations.py",
"/home/frank/Desktop/interface_lastversion/utils/datasets.py",
"/home/frank/Desktop/interface_lastversion/utils/general.py",
"/home/frank/Desktop/interface_lastversion/utils/google_utils.py",
"/home/frank/Desktop/interface_lastversion/utils/kmeans_for_anchors.py",
"/home/frank/Desktop/interface_lastversion/utils/metrics.py",
"/home/frank/Desktop/interface_lastversion/utils/torch_utils.py",
"/home/frank/Desktop/interface_lastversion/utils/__init__.py"],
    pathex=["/home/frank/Desktop/interface_lastversion"],
    binaries=[],
    datas=[("/home/frank/Desktop/interface_lastversion/best.pt","weights"),
("/home/frank/Desktop/interface_lastversion/styleSheet.qss","stylesheet")],
    hiddenimports=['models.yolo','shapely'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='mainapp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='mainapp',
)
