# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['mainapp.py',
	"C:\\Users\\86139\\Downloads\\interface\\bestpatch.py",
	"C:\\Users\\86139\\Downloads\\interface\\configuration.py",
	"C:\\Users\\86139\\Downloads\\interface\\detect.py",
	"C:\\Users\\86139\\Downloads\\interface\\fillfront.py",
	"C:\\Users\\86139\\Downloads\\interface\\Graphicview.py",
	"C:\\Users\\86139\\Downloads\\interface\\image_merge.py",
	"C:\\Users\\86139\\Downloads\\interface\\image_split.py",
	"C:\\Users\\86139\\Downloads\\interface\\inpainting.py",
	"C:\\Users\\86139\\Downloads\\interface\\Insertion_db.py",
	"C:\\Users\\86139\\Downloads\\interface\\Listwidget.py",
	"C:\\Users\\86139\\Downloads\\interface\\Listwidgetitem.py",
	"C:\\Users\\86139\\Downloads\\interface\\priorities.py",
"C:\\Users\\86139\\Downloads\\interface\\Tablewidget.py",
"C:\\Users\\86139\\Downloads\\interface\\Thread.py",
"C:\\Users\\86139\\Downloads\\interface\\Thread_inpainting.py",
"C:\\Users\\86139\\Downloads\\interface\\Treeview.py",
"C:\\Users\\86139\\Downloads\\interface\\update.py",
"C:\\Users\\86139\\Downloads\\interface\\models\\__init__.py",
"C:\\Users\\86139\\Downloads\\interface\\models\\common.py",
"C:\\Users\\86139\\Downloads\\interface\\models\\experimental.py",
"C:\\Users\\86139\\Downloads\\interface\\models\\export.py",
"C:\\Users\\86139\\Downloads\\interface\\models\\yolo.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\activations.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\datasets.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\general.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\google_utils.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\kmeans_for_anchors.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\metrics.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\torch_utils.py",
"C:\\Users\\86139\\Downloads\\interface\\utils\\__init__.py"],
    pathex=["C:\\Users\\86139\\Downloads\\interface"],
    binaries=[],
    datas=[("C:\\Users\\86139\\Downloads\\interface\\best.pt","weights"),
("C:\\Users\\86139\\Downloads\\interface\\styleSheet.qss","stylesheet")],
    hiddenimports=['models.yolo'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='mainapp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='mainapp',
)
